# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-05 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_uploadfile_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='institution',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
