# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0002_documents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
