# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-30 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import yournotes.models


class Migration(migrations.Migration):

    dependencies = [
        ('yournotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesupload',
            name='notefile',
            field=models.FileField(null=True, upload_to=yournotes.models.upload_location),
        ),
    ]
